#!/usr/bin/env python
# encoding: utf-8

#
# 發送聚會通告
#
# Author: 幸延 <a0726h77@gmail.com>, Chun-Yu Lee (Mat) <matlinuxer2@gmail.com>
# Copyright: 幸延 <a0726h77@gmail.com> || Chun-Yu Lee (Mat) <matlinuxer2@gmail.com>
# License: MIT
#

import common
from lib.Config import Config
from lib.Gmail import Gmail

PartyDate = common.thisThursday()

config = Config()
username = config['gmail']['username']
password = config['gmail']['password']
Sender = config['hackingthursday']['who']  # 值日生的 email
Reciver = config['hackingthursday']['email_address']
Subject = "HackingThursday 固定聚會 (%s)" % PartyDate

# 這裡改從網頁上將通告內文抓下來，以後改用網頁來更新通告。
Html = common.get_wikidot_content_body("http://www.hackingthursday.org/invite")
Txt = common.html2txt(Html)

if __name__ == "__main__":
    gmail = Gmail()
    gmail.login(username, password)
    gmail.send(Sender, Reciver, Subject, Txt, Html)
