#!/usr/bin/env python
# coding=utf8

#
# 發送聚會聚會手記
#
# Author: Chun-Yu Lee (Mat) <matlinuxer2@gmail.com>
# Copyright: Chun-Yu Lee (Mat) <matlinuxer2@gmail.com>
# License: MIT
#

import common
from lib.Config import Config
from lib.Gmail import Gmail

PartyDate = common.getThursday(0)

config = Config()
username = config['gmail']['username']
password = config['gmail']['password']
Sender = config['hackingthursday']['who']  # 值日生的 email
# Receiver = config['hackingthursday']['email_address']
Receiver = config['hackingthursday']['who']  # 值日生的 email
Subject = "HackingThursday 聚會手記 (%s)" % PartyDate

WikidotNoteURL = "http://www.hackingthursday.org/" + PartyDate
MailContentHeader = common.mail_content_header
MailContentFooter = common.mail_content_footer

Html = """
<html>
    <head>
        <title>HackingThursday</title>
    </head>
    <body>
    <pre>""" + MailContentHeader + """</pre>
    """ + WikidotNoteURL + """
    <pre>""" + MailContentFooter + """</pre>
    </body>
</html>
"""

Txt = common.html2txt(Html)

if __name__ == "__main__":
    gmail = Gmail()
    gmail.login(username, password)
    gmail.send(Sender, Receiver, Subject, Txt, Html)
