#!/usr/bin/env python
# coding:utf-8

#
# 讓聚會前將 wikidot 頁面準備好
#

# Author: 幸延 <a0726h77@gmail.com>
# Copyright: 幸延 <a0726h77@gmail.com>
# License: MIT

import sys
from xmlrpclib import ServerProxy
from common import *
from lib.Config import Config
from lib.Wikidot import Wikidot

config = Config()
user_app = config['wikidot']['wikidot_api_user']
key = config['wikidot']['wikidot_api_key']

tomorrow = thisThursday()
lastweek = prevThursday(tomorrow)
nextweek = nextThursday(tomorrow)
site = 'hackingthursday'
page = tomorrow
title = tomorrow + ' 聚會手記'
content = '''
[[[ %s |上一週]]] || [[[ %s |下一週]]]

[[toc]]

[[html]]
<iframe src='http://pad.hackingthursday.org?showControls=true&showChat=true&showLineNumbers=true&useMonospaceFont=false' width=675 height=400></iframe>
[[/html]]
''' % (lastweek, nextweek)

if __name__ == "__main__":
    wikidot = Wikidot()
    wikidot.auth(user_app, key)
    wikidot.set_site(site)

    # 如果頁面不存在，則建立當週筆記頁
    if not wikidot.get_page(page):
        if wikidot.save_page(page, title, content):
            print(('To view : http://%s.wikidot.com/%s' % (site, page)))
    else:
        print("筆記頁面已建立")

    # 更新上方選單項目
    top_bar_page = "nav:top"
    top_bar_title = 'Top Bar Menu'
    target_keyword = u"* [# 聚會手記]\n"
    note_page_link = u" * [[[" + tomorrow + "]]]\n"

    nav_top_page = wikidot.get_page(top_bar_page)
    nav_top_content = nav_top_page["content"]

    foundReturn = nav_top_content.find(tomorrow)
    if foundReturn < 0:
        new_nav_top_content = find_keyword_and_insert_content(nav_top_content, target_keyword, None, note_page_link)

        if wikidot.save_page(top_bar_page, top_bar_title, new_nav_top_content):
            print('To view : http://%s.wikidot.com/%s' % (site, top_bar_page))
    else:
        print("頁面的對應選單項目已建立")
