#!/usr/bin/env bash

CFG_FILE=$HOME/.config/h4-scripts/config.json
DATA_DIR=$HOME/.local/share/h4-scripts/
DEPENDS="jq curl" # Runtime dependencies

main() {
	local CHATID="$1"
	local TOKEN="$2"
	local TIMEOUT="10"
	local URL="https://api.telegram.org/bot$TOKEN/sendMessage"

	[ -n "$CHATID" ] || {
		echo "[ERR] Invalid Telegram's CHATID: $CHATID"
		return 1
	}

	[ -n "$TOKEN" ] || {
		echo "[ERR] Invalid Telegram's TOKEN: $TOKEN"
		return 1
	}

	tmpd=$(mktemp -d)
	(
		cat <<-"EOD" | sed -e "s/THIS_THURSDAY/$(date --iso-8601 -dthis-thursday)/g" >$tmpd/req01_body.dat
			[提醒通知] 本週四(THIS_THURSDAY)晚上 H4 一樣有聚會喔。相關資訊如下:
			- 線上共筆: https://pad.hackingthursday.org
			- 聚會通告: https://www.hackingthursday.org/invite
		EOD

		curl -s --max-time $TIMEOUT \
			-d chat_id=$CHATID \
			-d disable_web_page_preview=1 \
			-d parse_mode=HTML \
			--data-urlencode "text@$tmpd/req01_body.dat" \
			"$URL" >$tmpd/req01_stdout.dat 2>$tmpd/req01_stderr.dat
		echo $? >$tmpd/req01_retcode.dat
	)
	rm -r $tmpd
}

# Check dependencies
for dep in $DEPENDS; do
	which $dep >&/dev/null || {
		echo "[ERR] $dep is missing"
		exit 1
	}
done

# Check config file
[ -f "$CFG_FILE" ] || {
	echo "[ERR] Config file: $CFG_FILE is not found"
	exit 1
}

TELEGRAM_CHATID=$(cat $CFG_FILE | jq -Mr .TELEGRAM_CHATID | grep -v '^null$')
TELEGRAM_TOKEN=$(cat $CFG_FILE | jq -Mr .TELEGRAM_TOKEN | grep -v '^null$')

TASK_ID=$(echo "$(date --iso-8601=s) $RANDOM" | md5sum | cut -c-7)
logger -t "h4-scripts" ">>>> $TASK_ID begin at $(date --iso-8601=s)"
(
	main "$TELEGRAM_CHATID" "$TELEGRAM_TOKEN"
)
logger -t "h4-scripts" ">>>> $TASK_ID end at $(date --iso-8601=s)"
